services:
  cw_app: 
    container_name: "ClockwiseBackend"
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    restart: always
    depends_on: 
      - db
  db:
    container_name: "ClockwiseDB"
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
volumes:
  postgres-data: