services:
  cw-app: 
    container_name: "ClockwiseBackend"
    build: ./app/api/
    expose:
      - "8080"
    env_file:
      - .env
    restart: always
    depends_on: 
      - db
  db:
    container_name: "ClockwiseDB"
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
  cw-ml-service: 
    container_name: "MLService"
    build: ./app/ml/
    expose:
      - "8000"
    env_file: 
      - .env
    restart: always
    depends_on:
      - cw-app
  #Add FrontendService
  cw-web: 
    container_name: "ClockwiseFrontend"
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:${NGINX_PORT}
    depends_on:
      - cw-app
  nginx:
    container_name: "ClockwiseNginx"
    build: ./nginx/
    ports:
      - "${NGINX_PORT}:80"
    restart: always
    depends_on:
      - cw-app
      - cw-web
  #Add Redis Service
volumes:
  postgres-data: