services:
  db:
    container_name: "BitsShiftdb"
    image: postgres:12.4-alpine
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - ./.env
    restart: unless-stopped